#
# Makefile for the touchscreen drivers.
#

# Each configuration option enables a list of files.
obj-$(CONFIG_TOUCHSCREEN_IST30XX) += sec_touch.o

sec_touch-y := \
	ist30xx.o \
	ist30xx_update.o \
	ist30xx_tracking.o \
	ist30xx_misc.o \
	ist30xx_sec_test.o	\
	ist30xx_sys.o